bugfix: fixed an unused variable on non-debug builds
```
[...]/headers-more-nginx-module/src/ngx_http_headers_more_headers_in.c:766:24: error: variable 'nelts' set but not used [-Werror,-Wunused-but-set-variable]
    int                nelts;
                       ^
1 error generated.
```